### ISSUE TITLE
Simulation to experiment these RL algorithms

### ISSUE THREAD

**Issue by ramkumarkoppu** [noahfarr/rlx#2]
Is there any working simulator on Mac along with MLX RL?

**Comment by noahfarr** [comment]
What exactly to you mean by simulator? The implementations work with the [gymnasium](https://gymnasium.farama.org) interface.

**Comment by LeiHHHuang** [comment]
I guess @ramkumarkoppu meant simulator for robotics tasks, such as Pybullet and Mujoco.

**Comment by noahfarr** [comment]
Yeah as I said you can just build a custom gymnasium environment with mujoco and use that
